// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5mem78xilFZyCNBXvQjgT1fmNrMHlzcg',
    appId: '1:417035655423:web:09d06188c1c3120da954ca',
    messagingSenderId: '417035655423',
    projectId: 'app-medico-a5a6b',
    authDomain: 'app-medico-a5a6b.firebaseapp.com',
    storageBucket: 'app-medico-a5a6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe0mQicHAvAmqaGay7vKLsHWbwGAthmN0',
    appId: '1:417035655423:android:e4838814cbf0bf0aa954ca',
    messagingSenderId: '417035655423',
    projectId: 'app-medico-a5a6b',
    storageBucket: 'app-medico-a5a6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLPRyefMSEilfsdNJeCUdAvLl7SwS49ao',
    appId: '1:417035655423:ios:11a482568ae9e663a954ca',
    messagingSenderId: '417035655423',
    projectId: 'app-medico-a5a6b',
    storageBucket: 'app-medico-a5a6b.appspot.com',
    iosClientId: '417035655423-funltuifebce1fdq0hga4s4me3d72teb.apps.googleusercontent.com',
    iosBundleId: 'com.example.appPrototipo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLPRyefMSEilfsdNJeCUdAvLl7SwS49ao',
    appId: '1:417035655423:ios:11a482568ae9e663a954ca',
    messagingSenderId: '417035655423',
    projectId: 'app-medico-a5a6b',
    storageBucket: 'app-medico-a5a6b.appspot.com',
    iosClientId: '417035655423-funltuifebce1fdq0hga4s4me3d72teb.apps.googleusercontent.com',
    iosBundleId: 'com.example.appPrototipo',
  );
}
